---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  syncPolicy:
    automated: {}
  project: default
  source:
    repoURL: https://github.com/otsuarez/gitops-demo.git
    # git@github.com:otsuarez/gitops-demo.git
    targetRevision: local
    path: addons/local
    # kustomize specific config
    kustomize:
      configMapGenerator:
        - name: cluster-cm
          literals:    
            - domain=local.gitops-demo.acme.com
      # not working:
      # resources:
      #   - domain-cm.yaml
      commonLabels:
        project: demo-gitops
        dev-environment: local
        demo-version: second
  destination:
    server: https://kubernetes.default.svc
    namespace: default


  # # Sync policy
  # syncPolicy:
  #   automated:
  #     prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
  #     selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

  # # Ignore differences at the specified json pointers
  # ignoreDifferences:
  # - group: apps
  #   kind: Deployment
  #   jsonPointers:
  #   - /spec/replicas
