apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons
spec:
  syncPolicy:
    automated: {}
  project: default
  source:
    repoURL: git@github.com:otsuarez/gitops-demo.git
    targetRevision: HEAD
    path: addons/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: default
