---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.3.6
- custom

resources:
- addons.yaml

generatorOptions:
  disableNameSuffixHash: true
