---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    # kustomize:
    #   commonLabels:
    #     dev-environment: local
    #     project: demo-gitops
    path: addons/local
    repoURL: git@github.com:otsuarez/gitops-demo.git
    targetRevision: local
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
